site_name: 'SLAC OCIO DevOps/Developer Documentation'
site_descrition: 'Online version of Documentation for SLAC-OCIO DevOps Team'
site_author: "Vincent Flesouras"
theme: readthedocs
repo_name: 'GitHub'
repo_url: 'https://github.com/SLAC-OCIO/dev-processes'
include_search: true
pages:
  - Home: index.md
  - About:
    - 'About this Documentation': 'about/meta.md'
  - External Collaboration:
    - 'OCIO External Development Processes': 'ext-collab/COMS_GIT.md'
  - Drupal:
    - 'Overview of Drupal at SLAC': 'drupal/drupal-overview.md'
    - 'Linux Development Machine Configuration': 'drupal/mamp-linux.md'
    - 'OS-X Development Machine Configuration': 'drupal/grail.md'
    - 'Up and Running with SLAC Sites': 'drupal/slac_sites.md'
    - 'Upgrade/Patch Drupal': 'drupal/drupal_update.md'
  - DevOpsTeam:
    - 'Overview of Drupal for DevOps Team':  'core-team/overview.md'
    - 'Deployment of Vendor Pull Request': 'core-team/VENDOR_PR.md'
    - 'Deployment of Production from Vendor': 'core-team/VENDOR_DEPLOY.md'
    - 'Drupal Production Site': 'core-team/drupal_prod.md'
  - Github:
    - 'Overview of Github at SLAC': 'github/gh-overview.md'
    - 'Request Access': 'github/gh-slac-request.md'
    - 'Teams': 'github/gh-teams.md'
    - 'Private vs Public Repositories': 'github/gh-priv-pub.md'
    - 'Gitiquette - CoExGisting': 'github/gh-coexgiting.md'
